
Read Diabetes Dataset and apply iloc and loc

In [ ]:
import pandas as pd
import numpy as np

# Read dataset
df = pd.read_csv("Diabetes Dataset.csv")

# Preview data
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.shape          # rows & columns

(768, 9)

In [ ]:
df.columns        # column names

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:

df.info()         # data types & nulls

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
df.describe()     # statistical summary

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
#iloc & loc Operations (Index-based)
# Select first 5 rows
df.iloc[:5]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
#Select last row
df.iloc[-1]

Pregnancies                  1.000
Glucose                     93.000
BloodPressure               70.000
SkinThickness               31.000
Insulin                      0.000
BMI                         30.400
DiabetesPedigreeFunction     0.315
Age                         23.000
Outcome                      0.000
Name: 767, dtype: float64

In [ ]:
#Select rows 2–6 and columns 1–4
df.iloc[2:7, 1:5]

   Glucose  BloodPressure  SkinThickness  Insulin
2      183             64              0        0
3       89             66             23       94
4      137             40             35      168
5      116             74              0        0
6       78             50             32       88

In [ ]:
#Select only the first column
df.iloc[:, 0]

0       6
1       1
2       8
3       1
4       0
       ..
763    10
764     2
765     5
766     1
767     1
Name: Pregnancies, Length: 768, dtype: int64

In [ ]:
#Get value of Glucose in 3rd row
df.iloc[2]["Glucose"]

np.float64(183.0)

In [ ]:
#Select all rows where Outcome = 1 (Diabetic)
df.loc[df["Outcome"] == 1]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
766,1,126,60,0,0,30.1,0.349,47,1

In [ ]:
#Select Glucose & BMI for diabetic patients
df.loc[df["Outcome"] == 1, ["Glucose", "BMI"]]

     Glucose   BMI
0        148  33.6
2        183  23.3
4        137  43.1
6         78  31.0
8        197  30.5
..       ...   ...
755      128  36.5
757      123  36.3
759      190  35.5
761      170  44.0
766      126  30.1

[268 rows x 2 columns]

In [ ]:
#Select rows where Age > 40
df.loc[df["Age"] > 40]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
...,...,...,...,...,...,...,...,...,...
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
763,10,101,76,48,180,32.9,0.171,63,0
766,1,126,60,0,0,30.1,0.349,47,1

In [ ]:
#Select rows where BMI > 30 AND Outcome = 1
df.loc[(df["BMI"] > 30) & (df["Outcome"] == 1)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
11,10,168,74,0,0,38.0,0.537,34,1
...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
766,1,126,60,0,0,30.1,0.349,47,1

In [ ]:
#Glucose level between 100 and 140
df[df["Glucose"].between(100, 140)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
7,10,115,0,0,0,35.3,0.134,29,0
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
...,...,...,...,...,...,...,...,...,...
758,1,106,76,0,0,37.5,0.197,26,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1

In [ ]:
#Patients with zero insulin (data quality check)
df[df["Insulin"] == 0]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
5,5,116,74,0,0,25.6,0.201,30,0
7,10,115,0,0,0,35.3,0.134,29,0
...,...,...,...,...,...,...,...,...,...
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
764,2,122,70,27,0,36.8,0.340,27,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
#Patients with BloodPressure < 80 OR BMI > 35
df[(df["BloodPressure"] < 80) | (df["BMI"] > 35)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
#Replace zero BMI values with mean BMI
mean_bmi = df["BMI"].mean()
df.loc[df["BMI"] == 0, "BMI"] = mean_bmi

In [ ]:
#Sort by Glucose (descending)
df.sort_values(by="Glucose", ascending=False)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
661,1,199,76,43,0,42.9,1.394,22,1
561,0,198,66,32,274,41.3,0.502,28,1
579,2,197,70,99,0,34.7,0.575,62,1
228,4,197,70,39,744,36.7,2.329,31,0
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
182,1,0,74,20,23,27.7,0.299,21,0
342,1,0,68,35,0,32.0,0.389,22,0
349,5,0,80,32,0,41.0,0.346,37,1
75,1,0,48,20,0,24.7,0.140,22,0
502,6,0,68,41,0,39.0,0.727,41,1

In [ ]:
#Top 5 patients with highest BMI
df.sort_values(by="BMI", ascending=False).head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
177,0,129,110,46,130,67.1,0.319,26,1
445,0,180,78,63,14,59.4,2.420,25,1
673,3,123,100,35,240,57.3,0.880,22,0
125,1,88,30,42,99,55.0,0.496,26,1
120,0,162,76,56,100,53.2,0.759,25,1

In [ ]:
#Count diabetic vs non-diabetic
df["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
#Average Glucose per Outcome
df.groupby("Outcome")["Glucose"].mean()

Outcome
0    109.980000
1    141.257463
Name: Glucose, dtype: float64

In [ ]:
#Mean BMI and Age per Outcome
df.groupby("Outcome")[["BMI", "Age"]].mean()

               BMI        Age
Outcome
0        30.880066  31.190000
1        35.381288  37.067164

In [ ]:
# Create Age Group column
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[20, 30, 40, 50, 60, 100],
    labels=["20-30", "30-40", "40-50", "50-60", "60+"]
)

In [ ]:
#Count patients per Age Group
df["AgeGroup"].value_counts()

AgeGroup
20-30    417
30-40    157
40-50    113
50-60     54
60+       27
Name: count, dtype: int64

In [ ]:
#Check missing values
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
AgeGroup                    0
dtype: int64

In [ ]:
#Count zero values per column
(df == 0).sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
AgeGroup                      0
dtype: int64

In [ ]:
# Diabetic patients with high glucose & BMI
df[(df["Outcome"] == 1) & (df["Glucose"] > 140) & (df["BMI"] > 30)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,AgeGroup
0,6,148,72,35,0,33.6,0.627,50,1,40-50
8,2,197,70,45,543,30.5,0.158,53,1,50-60
11,10,168,74,0,0,38.0,0.537,34,1,30-40
13,1,189,60,23,846,30.1,0.398,59,1,50-60
22,7,196,90,0,0,39.8,0.451,41,1,40-50
...,...,...,...,...,...,...,...,...,...,...
748,3,187,70,22,200,36.4,0.408,36,1,30-40
753,0,181,88,44,510,43.3,0.222,26,1,20-30
754,8,154,78,32,0,32.4,0.443,45,1,40-50
759,6,190,92,0,0,35.5,0.278,66,1,60+
761,9,170,74,31,0,44.0,0.403,43,1,40-50

In [ ]:
# Oldest diabetic patient
df[df["Outcome"] == 1].sort_values("Age", ascending=False).head(1)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,AgeGroup
666,4,145,82,18,0,32.5,0.235,70,1,60+