Create a dictionary with this information:
"OrderID": [101, 102, 103, 104, 105],

    "Customer": ["Ali", "Sara", "Omar", "Mona", "Youssef"],

    "City": ["Cairo", "Giza", "Alex", "Cairo", "Giza"],

    "Amount": [250, 400, 150, 300, 500],

    "OrderDate": [ "2024-01-10","2024-01-12","2024-02-05","2024-02-20","2024-03-01“]

Convert this dictionary to data frame,

Convert data frame into a csv file,

Read csv file and apply these steps:

•Select the first 3 rows using iloc.

•Select the last row using iloc.

•Select rows 1 to 3 and columns Customer and Amount using iloc.

•Select only the Amount column using iloc.

•Get the value of City in the 3rd row using iloc.

•Select all rows where City = "Cairo".

•Select Customer and Amount for rows where Amount > 300.

•Select rows with OrderID 102 and 105.

•Update Amount to 600 where Customer = "Sara".

•Select all rows where City is not "Giza".

•Select orders with Amount between 200 and 400.

•Select orders from Cairo OR Giza.

•Select rows where Customer name starts with "M".

•Select rows where City is Cairo AND Amount > 250.

•Sort the DataFrame by Amount (descending) and select top 3 rows.

•Select orders made in January 2024.

•Select orders made after 2024-02-01.

•Add a new column Month extracted from OrderDate.

•Select orders made on a Monday.

•Count number of orders per month.

•Select the first order of each month.

•Select orders where day of month > 15.

•Find the total Amount per City per month.

•Select rows where OrderDate is the last day of the month.

•Select orders placed in the last 7 days of available data.

In [ ]:


import pandas as pd

# Create dictionary
data = {
    "OrderID": [101, 102, 103, 104, 105],
    "Customer": ["Ali", "Sara", "Omar", "Mona", "Youssef"],
    "City": ["Cairo", "Giza", "Alex", "Cairo", "Giza"],
    "Amount": [250, 400, 150, 300, 500],
    "OrderDate": [
        "2024-01-10",
        "2024-01-12",
        "2024-02-05",
        "2024-02-20",
        "2024-03-01"
    ]
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Convert OrderDate to datetime
df["OrderDate"] = pd.to_datetime(df["OrderDate"])

In [ ]:
df.to_csv("orders.csv", index=False)

df = pd.read_csv("orders.csv")
df["OrderDate"] = pd.to_datetime(df["OrderDate"])

In [ ]:
# Select first 3 rows
df.iloc[:3]

   OrderID Customer   City  Amount  OrderDate
0      101      Ali  Cairo     250 2024-01-10
1      102     Sara   Giza     400 2024-01-12
2      103     Omar   Alex     150 2024-02-05

In [ ]:
#Select last row
df.iloc[-1]

OrderID                      105
Customer                 Youssef
City                        Giza
Amount                       500
OrderDate    2024-03-01 00:00:00
Name: 4, dtype: object

In [ ]:
#Rows 1–3 & columns Customer and Amount
df.iloc[1:4, [1, 3]]

  Customer  Amount
1     Sara     400
2     Omar     150
3     Mona     300

In [ ]:
#Select only Amount column
df.iloc[:, 3]

0    250
1    400
2    150
3    300
4    500
Name: Amount, dtype: int64

In [ ]:
#City value in 3rd row
df.iloc[2]["City"]

'Alex'

In [ ]:
#Rows where City = Cairo
df[df["City"] == "Cairo"]

   OrderID Customer   City  Amount  OrderDate
0      101      Ali  Cairo     250 2024-01-10
3      104     Mona  Cairo     300 2024-02-20

In [ ]:
#Customer & Amount where Amount > 300
df.loc[df["Amount"] > 300, ["Customer", "Amount"]]

  Customer  Amount
1     Sara     400
4  Youssef     500

In [ ]:
#Rows with OrderID 102 and 105
df[df["OrderID"].isin([102, 105])]

   OrderID Customer  City  Amount  OrderDate
1      102     Sara  Giza     400 2024-01-12
4      105  Youssef  Giza     500 2024-03-01

In [ ]:
#Update Amount to 600 where Customer = Sara
df.loc[df["Customer"] == "Sara", "Amount"] = 600

In [ ]:
#City is NOT Giza
df[df["City"] != "Giza"]

   OrderID Customer   City  Amount  OrderDate
0      101      Ali  Cairo     250 2024-01-10
2      103     Omar   Alex     150 2024-02-05
3      104     Mona  Cairo     300 2024-02-20

In [ ]:
#Amount between 200 and 400
df[df["Amount"].between(200, 400)]

   OrderID Customer   City  Amount  OrderDate
0      101      Ali  Cairo     250 2024-01-10
3      104     Mona  Cairo     300 2024-02-20

In [ ]:
#City Cairo OR Giza
df[df["City"].isin(["Cairo", "Giza"])]

   OrderID Customer   City  Amount  OrderDate
0      101      Ali  Cairo     250 2024-01-10
1      102     Sara   Giza     600 2024-01-12
3      104     Mona  Cairo     300 2024-02-20
4      105  Youssef   Giza     500 2024-03-01

In [ ]:
#Customer name starts with "M"
df[df["Customer"].str.startswith("M")]

   OrderID Customer   City  Amount  OrderDate
3      104     Mona  Cairo     300 2024-02-20

In [ ]:
#City Cairo AND Amount > 250
df[(df["City"] == "Cairo") & (df["Amount"] > 250)]

   OrderID Customer   City  Amount  OrderDate
3      104     Mona  Cairo     300 2024-02-20

In [ ]:
#Sort by Amount (descending) & top 3
df.sort_values(by="Amount", ascending=False).head(3)

   OrderID Customer   City  Amount  OrderDate
1      102     Sara   Giza     600 2024-01-12
4      105  Youssef   Giza     500 2024-03-01
3      104     Mona  Cairo     300 2024-02-20

In [ ]:
#Orders made in January 2024
df[(df["OrderDate"].dt.month == 1) & (df["OrderDate"].dt.year == 2024)]

   OrderID Customer   City  Amount  OrderDate
0      101      Ali  Cairo     250 2024-01-10
1      102     Sara   Giza     600 2024-01-12

In [ ]:
#Orders after 2024-02-01
df[df["OrderDate"] > "2024-02-01"]

   OrderID Customer   City  Amount  OrderDate
2      103     Omar   Alex     150 2024-02-05
3      104     Mona  Cairo     300 2024-02-20
4      105  Youssef   Giza     500 2024-03-01

In [ ]:
#Add Month column
df["Month"] = df["OrderDate"].dt.month

In [ ]:
#Orders made on Monday
df[df["OrderDate"].dt.day_name() == "Monday"]

   OrderID Customer  City  Amount  OrderDate  Month
2      103     Omar  Alex     150 2024-02-05      2

In [ ]:
#Count orders per month
df.groupby(df["OrderDate"].dt.month).size()

OrderDate
1    2
2    2
3    1
dtype: int64

In [ ]:
#First order of each month
df.sort_values("OrderDate").groupby(df["OrderDate"].dt.month).first()

           OrderID Customer   City  Amount  OrderDate  Month
OrderDate
1              101      Ali  Cairo     250 2024-01-10      1
2              103     Omar   Alex     150 2024-02-05      2
3              105  Youssef   Giza     500 2024-03-01      3

In [ ]:
#Orders where day > 15
df[df["OrderDate"].dt.day > 15]

   OrderID Customer   City  Amount  OrderDate  Month
3      104     Mona  Cairo     300 2024-02-20      2

In [ ]:
#Total Amount per City per month
df.groupby([df["OrderDate"].dt.month, "City"])["Amount"].sum()

OrderDate  City
1          Cairo    250
           Giza     600
2          Alex     150
           Cairo    300
3          Giza     500
Name: Amount, dtype: int64

In [ ]:
#Orders on last day of month
df[df["OrderDate"].dt.is_month_end]

Empty DataFrame
Columns: [OrderID, Customer, City, Amount, OrderDate, Month]
Index: []

In [ ]:
#Orders in last 7 days of available data
last_date = df["OrderDate"].max()
df[df["OrderDate"] >= last_date - pd.Timedelta(days=7)]

   OrderID Customer  City  Amount  OrderDate  Month
4      105  Youssef  Giza     500 2024-03-01      3